movieproject/movieapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='movieapp'
urlpatterns = [
    path('', views.index,name='index'),
    path('movie/<int:movie_id>/', views.detail,name='detail'),
    path('movies/<int:movie_id>/', views.getMovie,name='getMovie'),
    path('add/', views.add_movie,name='add_movie'),
    path('update/<int:id>/', views.updateMovie,name='update'),
    path('delete/<int:id>/', views.delete,name='delete'),
]

movieproject/movieproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from movieproject import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from .models import Movie


# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, "index.html", context)


def detail(request, movie_id):
    return HttpResponse("this is movie no %s" % movie_id)


def getMovie(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "movie_detail.html", {'movie': movie})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        descr = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['image']

        movie = Movie(name=name, desc=descr, year=year, img=img)
        movie.save()
    return render(request, 'add.html')


def updateMovie(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'forms': form, 'movie': movie})

def delete(request,id):
    if request.method=='POST':
        movieid= Movie.objects.get(id=id)
        movieid.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name">
    <input type="text" name="desc" placeholder="enter movie desc">
    <input type="text" name="year" placeholder="enter movie year">

    <input type="file" name="image" >

    <input type="submit">
</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Online Movie Store
  </a>
</nav>

{% block body %}
{% endblock %}


</body>
</html>

movieproject/templates/delete.html
<form method="post">
  {% csrf_token %}
  Are you sure you want to delete this movie?
  <input type="submit">

</form>

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{forms.as_p}}
    <input type="submit">
</form>

{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" >
                <img src="{{i.img.url}}" class="card-img-top" alt="..." height="250">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.desc}}</p>
                    <a href="{% url 'movieapp:getMovie' i.id %}" class="btn btn-primary">details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% for i in movie_list %}
{{i.id}} -  {{i.name}}  -  {{i.desc}} <br>
{% endfor %}
{% for i in movie_list %}
<a href="movie/{{i.id}}">{{i.name}}</a> <br>
{% endfor %}
for getting details<br>
{% for i in movie_list %}
<a href="movies/{{i.id}}">{{i.name}}</a> <br>
{% endfor %}

for getting details another<br>
{% for i in movie_list %}
<img src="{{i.img.url}}" width="100" height="100">
<a href="{% url 'movieapp:getMovie' i.id %}">{{i.name}} click here</a> <br>
{% endfor %}
{% endblock %}

movieproject/templates/movie_detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">

            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-6">
            <h3>{{movie.name}}<br></h3>

            <h4>{{movie.desc}}<br></h4>
            {{movie.year}}<br>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>

        </div>
    </div>
</div>
{% endblock %}